server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: meal_order
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meal_order?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&serverTimezone=GMT%2b8
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.163.com
    username: xiexinquan520@163.com
    password: QKFUWKSRMXJHUZZG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  file:
    name: meal_order.log
    max-history: 2
    max-size: 100MB
    path: ./logs/
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  com.quan: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: trace

